inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.2.5
  NewCops: disable
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 18

Metrics/ParameterLists:
  Enabled: true
  CountKeywordArgs: false

require: rubocop-rspec
