name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish gem to RubyGems.org
    runs-on: ubuntu-latest

    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # IMPORTANT: this permission is required for `rake release` to push the release tag

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec

      - name: Run lint
        run: bundle exec rubocop

      - name: Release gem
        uses: rubygems/release-gem@v1
